import "../style/globals.css";
import "react-toastify/dist/ReactToastify.css";

import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Test ADS FE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-full flex flex-col grow">
        {children}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          closeOnClick
          draggable={false}
          pauseOnHover
          theme="colored"
        />
      </body>
    </html>
  );
}
